//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenpressoKG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenpressoKG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bch {
            get {
                object obj = ResourceManager.GetObject("bch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_header {
            get {
                object obj = ResourceManager.GetObject("bg_header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btc {
            get {
                object obj = ResourceManager.GetObject("btc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abort.
        /// </summary>
        internal static string btn__template_abort {
            get {
                return ResourceManager.GetString("btn_ template_abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Block Host.
        /// </summary>
        internal static string btn_bhost_block {
            get {
                return ResourceManager.GetString("btn_bhost_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View Host.
        /// </summary>
        internal static string btn_bhost_viewfile {
            get {
                return ResourceManager.GetString("btn_bhost_viewfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string btn_license_copy {
            get {
                return ResourceManager.GetString("btn_license_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Generate.
        /// </summary>
        internal static string btn_license_generate {
            get {
                return ResourceManager.GetString("btn_license_generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string btn_template_cancel {
            get {
                return ResourceManager.GetString("btn_template_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ignore.
        /// </summary>
        internal static string btn_template_ignore {
            get {
                return ResourceManager.GetString("btn_template_ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No.
        /// </summary>
        internal static string btn_template_no {
            get {
                return ResourceManager.GetString("btn_template_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string btn_template_ok {
            get {
                return ResourceManager.GetString("btn_template_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retry.
        /// </summary>
        internal static string btn_template_retry {
            get {
                return ResourceManager.GetString("btn_template_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        internal static string btn_template_yes {
            get {
                return ResourceManager.GetString("btn_template_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chat {
            get {
                object obj = ResourceManager.GetObject("chat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eth {
            get {
                object obj = ResourceManager.GetObject("eth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exclamation {
            get {
                object obj = ResourceManager.GetObject("exclamation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPG KeyID.
        /// </summary>
        internal static string lbl_about_gpg {
            get {
                return ResourceManager.GetString("lbl_about_gpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational purposes only. No ads, no music, no bullshit..
        /// </summary>
        internal static string lbl_about_HeaderSub {
            get {
                return ResourceManager.GetString("lbl_about_HeaderSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signature Thumbprint.
        /// </summary>
        internal static string lbl_about_thumbprint {
            get {
                return ResourceManager.GetString("lbl_about_thumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform this step first to block {0} from communicating with your computer. Required for license activation to work..
        /// </summary>
        internal static string lbl_bhost_pnl_intro {
            get {
                return ResourceManager.GetString("lbl_bhost_pnl_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Blocker.
        /// </summary>
        internal static string lbl_bhost_pnl_title {
            get {
                return ResourceManager.GetString("lbl_bhost_pnl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCH.
        /// </summary>
        internal static string lbl_contrib_bch {
            get {
                return ResourceManager.GetString("lbl_contrib_bch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTC.
        /// </summary>
        internal static string lbl_contrib_btc {
            get {
                return ResourceManager.GetString("lbl_contrib_btc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETH.
        /// </summary>
        internal static string lbl_contrib_eth {
            get {
                return ResourceManager.GetString("lbl_contrib_eth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated License Key.
        /// </summary>
        internal static string lbl_generate_license {
            get {
                return ResourceManager.GetString("lbl_generate_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lbl_generate_name {
            get {
                return ResourceManager.GetString("lbl_generate_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Repo.
        /// </summary>
        internal static string lnk_about_github {
            get {
                return ResourceManager.GetString("lnk_about_github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPB Profile.
        /// </summary>
        internal static string lnk_about_tpb {
            get {
                return ResourceManager.GetString("lnk_about_tpb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your host file has been left untouched.
        /// </summary>
        internal static string msgbox_bhost_cancel_msg {
            get {
                return ResourceManager.GetString("msgbox_bhost_cancel_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Cancelled.
        /// </summary>
        internal static string msgbox_bhost_cancel_title {
            get {
                return ResourceManager.GetString("msgbox_bhost_cancel_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate the exact path to Screenpresso. Skipping Firewall registration. You may need to manually block Screenpresso using Windows Firewall.
        ///
        ///This can happen if you&apos;re running Screenpresso Portable.
        ///
        ///{0}.
        /// </summary>
        internal static string msgbox_bhost_fw_badpath_msg {
            get {
                return ResourceManager.GetString("msgbox_bhost_fw_badpath_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Firewall Target.
        /// </summary>
        internal static string msgbox_bhost_fw_badpath_title {
            get {
                return ResourceManager.GetString("msgbox_bhost_fw_badpath_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added new Firewall rules to block the executable:
        ///
        ///{0}.
        /// </summary>
        internal static string msgbox_bhost_fw_success_msg {
            get {
                return ResourceManager.GetString("msgbox_bhost_fw_success_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Firewall Rules.
        /// </summary>
        internal static string msgbox_bhost_fw_success_title {
            get {
                return ResourceManager.GetString("msgbox_bhost_fw_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully edited your host file at {0}.
        /// </summary>
        internal static string msgbox_bhost_success_msg {
            get {
                return ResourceManager.GetString("msgbox_bhost_success_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenpresso Successfully Blocked.
        /// </summary>
        internal static string msgbox_bhost_success_title {
            get {
                return ResourceManager.GetString("msgbox_bhost_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Screenpresso Blocks?.
        /// </summary>
        internal static string msgbox_bhost_title {
            get {
                return ResourceManager.GetString("msgbox_bhost_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will block Screenpresso by adding entries to your Windows host file. 
        ///
        ///Additionally, two firewall rules will be created which blocks inbound / outbound internet communication between your machine and Screenpresso only. This ensures the Screenpresso License server doesn&apos;t deactivate you.
        ///
        ///Are you sure?.
        /// </summary>
        internal static string msgbox_block_msg {
            get {
                return ResourceManager.GetString("msgbox_block_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot copy a license key you have not generated yet..
        /// </summary>
        internal static string msgbox_copy_invlicense_msg {
            get {
                return ResourceManager.GetString("msgbox_copy_invlicense_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No License Generated.
        /// </summary>
        internal static string msgbox_copy_invlicense_title {
            get {
                return ResourceManager.GetString("msgbox_copy_invlicense_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located {0} with Windows Env Var in:
        ///
        ///{1}.
        /// </summary>
        internal static string msgbox_debug_fpath_env_c1_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_env_c1_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: 1000C-1.
        /// </summary>
        internal static string msgbox_debug_fpath_env_c1_title {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_env_c1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located {0} with Windows Env Var in:
        ///
        ///{1}.
        /// </summary>
        internal static string msgbox_debug_fpath_env_c2_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_env_c2_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: 1000C-2.
        /// </summary>
        internal static string msgbox_debug_fpath_env_c2_title {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_env_c2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located {0} In:
        ///
        ///{1}.
        /// </summary>
        internal static string msgbox_debug_fpath_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located {0} with Powershell in:
        ///
        ///{1}.
        /// </summary>
        internal static string msgbox_debug_fpath_ps_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_ps_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: 1000B.
        /// </summary>
        internal static string msgbox_debug_fpath_ps_title {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_ps_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: 1000A.
        /// </summary>
        internal static string msgbox_debug_fpath_title {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears something went wrong adding the new firewall rules.
        ///
        ///It could either be that you&apos;ve already added the rules in a prior session, or you are running Screenpresso Portable and can&apos;t find the exact location.
        ///
        ///You can manually block Screenpresso in your WIndows Firewall..
        /// </summary>
        internal static string msgbox_debug_ps_bhost_qry_alert_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_ps_bhost_qry_alert_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall Rule Addition Failed.
        /// </summary>
        internal static string msgbox_debug_ps_bhost_qry_alert_title {
            get {
                return ResourceManager.GetString("msgbox_debug_ps_bhost_qry_alert_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added firewall rules to system:
        ///
        ///{0}
        ///
        ///{1}.
        /// </summary>
        internal static string msgbox_debug_ps_bhost_qry_ok_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_ps_bhost_qry_ok_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Firewall Updated.
        /// </summary>
        internal static string msgbox_debug_ps_bhost_qry_ok_title {
            get {
                return ResourceManager.GetString("msgbox_debug_ps_bhost_qry_ok_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string msgbox_debug_ps_output_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_ps_output_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: PowerShell Output.
        /// </summary>
        internal static string msgbox_debug_ps_output_title {
            get {
                return ResourceManager.GetString("msgbox_debug_ps_output_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a name first before trying to generate a license key..
        /// </summary>
        internal static string msgbox_generate_invalidname_msg {
            get {
                return ResourceManager.GetString("msgbox_generate_invalidname_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Name Specified.
        /// </summary>
        internal static string msgbox_generate_invalidname_title {
            get {
                return ResourceManager.GetString("msgbox_generate_invalidname_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key generation failed.
        /// </summary>
        internal static string status_keygen_fail {
            get {
                return ResourceManager.GetString("status_keygen_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key generation successful.
        /// </summary>
        internal static string status_keygen_succ {
            get {
                return ResourceManager.GetString("status_keygen_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate license key first.
        /// </summary>
        internal static string statusbar_copy_invalidlicense {
            get {
                return ResourceManager.GetString("statusbar_copy_invalidlicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License key copied. Paste in Screenpresso app..
        /// </summary>
        internal static string statusbar_copy_succ {
            get {
                return ResourceManager.GetString("statusbar_copy_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Generate to create license key ....
        /// </summary>
        internal static string statusbar_generate {
            get {
                return ResourceManager.GetString("statusbar_generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number generated. Paste into Screenpresso app..
        /// </summary>
        internal static string statusbar_serial_generated {
            get {
                return ResourceManager.GetString("statusbar_serial_generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do this because I enjoy giving back, and I&apos;m not looking to make a profit off my work. However, donations would help immensely for one purpose -- purchasing libraries and other commercial products which have insane licensing systems. These types of products would make life much easier and get releases pumped out on a more regular basis. Don&apos;t feel obligated, this is just &quot;if you can&quot;. My main goal is better tools..
        /// </summary>
        internal static string txt_contrib_intro {
            get {
                return ResourceManager.GetString("txt_contrib_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Key could not be generated.
        /// </summary>
        internal static string txt_License_resp_keygen_fail {
            get {
                return ResourceManager.GetString("txt_License_resp_keygen_fail", resourceCulture);
            }
        }
    }
}
